baseurl: "https://kakkoyun.me"
title: "kakkoyun"
theme: "PaperMod"

languageCode: "en"
defaultContentLanguage: "en"
buildDrafts: true

pagination:
  pagerSize: 5

canonifyUrls: true

outputFormats:
  markdown:
    name: markdown
    baseName: index
    mediaType: text/markdown
    isPlainText: true

outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - MARKDOWN
  section:
    - HTML
    - MARKDOWN
  term:
    - HTML
    - MARKDOWN

markup:
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    # noClasses: false
    style: monokai
  goldmark:
    renderer:
      unsafe: true
menu:
  main:
    - name: "Now"
      weight: 10
      url: "/now/"
    - name: "About"
      weight: 11
      url: "/about/"
    # - name: "Uses"
    #   weight: 12
    #   url: "/uses/"
    # - name: "Blog"
    #   weight: 20
    #   url: "/tags/blog"
    # - name: "Open Source"
    #   weight: 30
    #   url: "/open_source/"
    - name: "Talks"
      weight: 40
      url: "/categories/talks"
    # - name: "Stats"
    #   weight: 50
    #   url: "/stats/"
    # - name: "Newsletter"
    #   weight: 70
    #   url: "/newsletter/"
    - name: "Notes"
      weight: 80
      url: "/notes/"
    # - name: "Sponsorship"
    #   weight: 90
    #   url: "/sponsorship/"
    - name: "Misc"
      weight: 100
      url: "/misc/"
    # - name: "Archives"
    #   weight: 101
    #   url: "/archives/"
    - name: "Search"
      weight: 102
      url: "/search/"

taxonomies:
  category: "categories"
  series: "series"
  tag: "tags"
  # author: "authors"

params:
  title: "Kemal Akkoyun"
  copyright: "Â© 2021-2025 Kemal Akkoyun"
  description: "Kemal Akkoyun's personal website"
  keywords:
    [
      "linux",
      "infrastructure",
      "database",
      "reliability",
      "go",
      "zig",
      "c",
      "rust",
      "programming",
      "blog",
      "developer",
      "software",
      "engineering",
      "monitoring",
      "observability",
      "ebpf",
      "profiling",
      "high-performance-computing",
      "HPC",
      "performance",
    ]
  defaultTheme: "auto"
  disableThemeToggle: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  disableAnchoredHeadings: false
  hideMetadata: false
  hideSummary: false
  dateFormat: "January 2, 2006"
  homeInfoParams:
    content: "If you like my work, let's stay in touch!"
  mainSections:
    - posts
    - notes
    - talks
  tocOpen: false
  showToc: true
  showRecentNotes: true
  showShareButtons: true
  showReadingTime: true
  showBreadCrumbs: false
  showCodeCopyButtons: true
  showWordCount: true
  showFullTextinRSS: true
  showRssButtonInSectionTermList: true
  comments: true
  giscus:
    repoId: "MDEwOlJlcG9zaXRvcnkyMzM4MDg0NjQ="
    category: "General"
    categoryId: "DIC_kwDODe-iUM4Cp6Wj"
    mapping: "title"
    strict: "0"
    reactionsEnabled: "1"
    theme: "preferred_color_scheme"
  editPost:
    URL: "https://github.com/kakkoyun/me/edit/master/content"
    Text: "Suggest Changes"
    appendFilePath: true
  socialIcons:
    - name: "Github"
      url: "https://github.com/kakkoyun"
    - name: "LinkedIn"
      url: "https://linkedin.com/in/kakkoyun"
    - name: "Bluesky"
      url: "https://bsky.app/profile/kakkoyun.me"
    - name: "X"
      url: "https://x.com/kakkoyun_me"
    - name: "Mastodon"
      url: "https://hachyderm.io/@kakkoyun"
    - name: "YouTube"
      url: "https://www.youtube.com/playlist?list=PL3P7-fer_ILLtH_ZtQDQhDAEgTo5r9OnB"
    - name: "Medium"
      url: "https://medium.com/@kakkoyun/"
    - name: "stackoverflow"
      url: "https://stackoverflow.com/users/1113525/kemal-akkoyun"
    - name: "ycombinator"
      url: "https://news.ycombinator.com/user?id=kakkoyun"
    - name: "RSS"
      url: "https://kakkoyun.me/index.xml"
      rel: "alternate"
      type: "application/rss+xml"
  analytics:
    plausible:
      domain: "kakkoyun.me"
      outboundLinksTracking: true
    hakanai:
      site: "d59129ee-cdfa-47a5-8908-5a017caf60c7"
  assets:
    favicon: "img/favicon.ico"
    theme_color: "#000000"
  label:
    text: "kakkoyun"
    icon: "img/favicon-64x64.png"
    icon_height: "64"
